# -*- coding: utf-8 -*-
"""sympy matrix.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hbmfju41UjTqCNohy5gGDFdrTfhxF_gv
"""

import torch

import tensorflow as tf

import numpy as np

import sympy

xMatrix = sympy.Matrix([[1, 2, 3],[1,2, 2]])

xMatrix

scalar = int(1)

vector = [1,2,3]

matrix = [ vector_1, vector_2, vector_3 ]